# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1093, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLayout_horizontal = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLayout_horizontal.setContentsMargins(0, 0, 0, 0)
        self.mainLayout_horizontal.setObjectName("mainLayout_horizontal")
        self.imageListWidget = QtWidgets.QVBoxLayout()
        self.imageListWidget.setObjectName("imageListWidget")
        self.imageList_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.imageList_listWidget.setObjectName("imageList_listWidget")
        self.imageListWidget.addWidget(self.imageList_listWidget)
        self.importImagesButton_push = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.importImagesButton_push.setObjectName("importImagesButton_push")
        self.imageListWidget.addWidget(self.importImagesButton_push)
        self.loadImageButton_push = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadImageButton_push.setObjectName("loadImageButton_push")
        self.imageListWidget.addWidget(self.loadImageButton_push)
        self.removeImageButton_push = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.removeImageButton_push.setObjectName("removeImageButton_push")
        self.imageListWidget.addWidget(self.removeImageButton_push)
        self.mainLayout_horizontal.addLayout(self.imageListWidget)
        self.slidersWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.slidersWidget.setObjectName("slidersWidget")
        self.slidersLayout_horizontal = QtWidgets.QHBoxLayout(self.slidersWidget)
        self.slidersLayout_horizontal.setContentsMargins(0, 0, 0, 0)
        self.slidersLayout_horizontal.setObjectName("slidersLayout_horizontal")
        self.zoomLayout_vertical = QtWidgets.QVBoxLayout()
        self.zoomLayout_vertical.setObjectName("zoomLayout_vertical")
        self.zoom_label = QtWidgets.QLabel(self.slidersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_label.sizePolicy().hasHeightForWidth())
        self.zoom_label.setSizePolicy(sizePolicy)
        self.zoom_label.setObjectName("zoom_label")
        self.zoomLayout_vertical.addWidget(self.zoom_label)
        self.zoomSlider_vertical = QtWidgets.QSlider(self.slidersWidget)
        self.zoomSlider_vertical.setOrientation(QtCore.Qt.Vertical)
        self.zoomSlider_vertical.setObjectName("zoomSlider_vertical")
        self.zoomLayout_vertical.addWidget(self.zoomSlider_vertical)
        self.slidersLayout_horizontal.addLayout(self.zoomLayout_vertical)
        self.mainLayout_horizontal.addWidget(self.slidersWidget)
        self.graphicWidget = QtWidgets.QVBoxLayout()
        self.graphicWidget.setObjectName("graphicWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicWidget.addWidget(self.graphicsView)
        self.selectionWidget = QtWidgets.QHBoxLayout()
        self.selectionWidget.setObjectName("selectionWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exportImageButton_push = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exportImageButton_push.setObjectName("exportImageButton_push")
        self.verticalLayout_2.addWidget(self.exportImageButton_push)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.selectionWidget.addLayout(self.verticalLayout_2)
        self.exportChoices = QtWidgets.QGridLayout()
        self.exportChoices.setObjectName("exportChoices")
        self.exportRegionRbutton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.exportRegionRbutton.setObjectName("exportRegionRbutton")
        self.exportChoices.addWidget(self.exportRegionRbutton, 0, 0, 1, 1)
        self.exportLineRbutton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.exportLineRbutton.setObjectName("exportLineRbutton")
        self.exportChoices.addWidget(self.exportLineRbutton, 0, 1, 1, 1)
        self.exportColumnRbutton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.exportColumnRbutton.setObjectName("exportColumnRbutton")
        self.exportChoices.addWidget(self.exportColumnRbutton, 1, 0, 1, 1)
        self.exportCharRbutton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.exportCharRbutton.setObjectName("exportCharRbutton")
        self.exportChoices.addWidget(self.exportCharRbutton, 1, 1, 1, 1)
        self.selectionWidget.addLayout(self.exportChoices)
        self.graphicWidget.addLayout(self.selectionWidget)
        self.graphicWidget.setStretch(0, 1)
        self.mainLayout_horizontal.addLayout(self.graphicWidget)
        self.mainLayout_horizontal.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.importImagesButton_push.setText(_translate("MainWindow", "Import Images"))
        self.loadImageButton_push.setText(_translate("MainWindow", "Load Image"))
        self.removeImageButton_push.setText(_translate("MainWindow", "Remove Image"))
        self.zoom_label.setText(_translate("MainWindow", "zoom"))
        self.exportImageButton_push.setText(_translate("MainWindow", "Export Selected Coordinates"))
        self.radioButton_2.setText(_translate("MainWindow", "Polygon Selector"))
        self.radioButton.setText(_translate("MainWindow", "Box Selector"))
        self.exportRegionRbutton.setText(_translate("MainWindow", "Region"))
        self.exportLineRbutton.setText(_translate("MainWindow", "Line"))
        self.exportColumnRbutton.setText(_translate("MainWindow", "Column"))
        self.exportCharRbutton.setText(_translate("MainWindow", "Character"))

